### ISSUE TITLE
Feature: Google calendar

### ISSUE THREAD

**Issue by euberdeveloper** [heddendorp/tumi-app#44]
It would be useful a button to add the event to Google calendar and not forget it

**Comment by heddendorp** [comment]
@euberdeveloper in your profile at https://tumi.esn.world/profile is a link that you can subscribe to with the google calendar already that will give you all the events you are registered for.
You can follow this guide here https://lauren-c-stephen.medium.com/subscribe-to-an-icalendar-feed-in-google-calendar-and-solve-update-issues-79b4e84b3c64

Feel free to reopen the issue if this does not solve your problem

**Comment by euberdeveloper** [comment]
It works, thanks
